# Generated by Django 5.1.5 on 2025-10-29 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OPBRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(choices=[('PRODUCTION_COMMERCIALIZATION', 'Production & Commercialization'), ('RECORDS_ARCHIVES', 'Records and Archives'), ('ALUMNI_AFFAIRS', 'Alumni Affairs'), ('BOARD_SECRETARY', 'Board Secretary'), ('CAS', 'College of Arts and Sciences'), ('MEDICAL_SERVICES', 'Medical Services Unit'), ('SUPERVISING_ADMIN', 'Supervising Administrative Office'), ('REGISTRAR', 'Registrar'), ('COLLEGE_IND_TECH', 'College of Industrial Technology'), ('CAWAYAN_CAMPUS', 'Cawayan Campus'), ('BUDGET_UNIT', 'Budget Unit'), ('INTERNATIONAL_RELATIONS', 'International Relations Office'), ('SPORTS_CULTURAL', 'Sports and Cultural Development'), ('LEGAL_SERVICES', 'Legal Services Office'), ('PERSONNEL_SCHOLARSHIP', 'Personnel Scholarship Office'), ('QUALITY_ASSURANCE', 'Quality Assurance Office')], max_length=50)),
                ('fiscal_year', models.CharField(default='2026', max_length=4)),
                ('unit', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('for-approval', 'For Approval'), ('enhancement', 'Enhancement')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opb_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OPBItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kra_no', models.CharField(blank=True, max_length=50, null=True)),
                ('objective_no', models.CharField(blank=True, max_length=50, null=True)),
                ('indicators', models.TextField(blank=True, null=True)),
                ('annual_target', models.TextField(blank=True, null=True)),
                ('activities', models.TextField(blank=True, null=True)),
                ('timeframe', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('source_of_fund', models.CharField(blank=True, max_length=200, null=True)),
                ('responsible_units', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.opbrequest')),
            ],
        ),
    ]
