# Generated by Django 5.1.5 on 2025-10-29 06:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(blank=True, choices=[('PRODUCTION_COMMERCIALIZATION', 'Production & Commercialization'), ('RECORDS_ARCHIVES', 'Records and Archives'), ('ALUMNI_AFFAIRS', 'Alumni Affairs'), ('BOARD_SECRETARY', 'Board Secretary'), ('CAS', 'College of Arts and Sciences'), ('MEDICAL_SERVICES', 'Medical Services Unit'), ('SUPERVISING_ADMIN', 'Supervising Administrative Office'), ('REGISTRAR', 'Registrar'), ('COLLEGE_IND_TECH', 'College of Industrial Technology'), ('CAWAYAN_CAMPUS', 'Cawayan Campus'), ('BUDGET_UNIT', 'Budget Unit'), ('INTERNATIONAL_RELATIONS', 'International Relations Office'), ('SPORTS_CULTURAL', 'Sports and Cultural Development'), ('LEGAL_SERVICES', 'Legal Services Office'), ('PERSONNEL_SCHOLARSHIP', 'Personnel Scholarship Office'), ('QUALITY_ASSURANCE', 'Quality Assurance Office')], max_length=50, null=True, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('unit_head', 'Unit Head')], default='unit_head', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
