# Generated by Django 5.2.7 on 2025-11-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('CAS', 'College of Arts and Sciences'), ('COLLEGE_IND_TECH', 'College of Industrial Technology'), ('COE', 'College of Education'), ('COA', 'College of Agriculture'), ('PRODUCTION_COMMERCIALIZATION', 'Production & Commercialization'), ('PRODUCTION_BAO', 'Production & Business Affairs Office'), ('PPSDO', 'Physical Plant & Site Development Office'), ('VETERINARY_SERVICES', 'Veterinary Services'), ('GUIDANCE', 'Guidance'), ('RECORDS_ARCHIVES', 'Records and Archives'), ('ALUMNI_AFFAIRS', 'Alumni Affairs'), ('BOARD_SECRETARY', 'Board Secretary'), ('MEDICAL_SERVICES', 'Medical Services Unit'), ('SUPERVISING_ADMIN', 'Supervising Administrative Office'), ('REGISTRAR', 'Registrar'), ('CAWAYAN_CAMPUS', 'Cawayan Campus'), ('BUDGET_UNIT', 'Budget Unit'), ('ACCOUNTING_UNIT', 'Accounting Unit'), ('CASH_UNIT', 'Cash Unit'), ('SUPPLY_UNIT', 'Supply Unit'), ('RECORDS_UNIT', 'Records Unit'), ('HRMO_OFFICE', 'HRMO Office'), ('PROCUREMENT_UNIT', 'Procurement Unit/BAC'), ('SECURITY_UNIT', 'Security Unit'), ('MOTORPOOL_UNIT', 'Motorpool Unit'), ('LIBRARY_SERVICES', 'Library Services'), ('NSTP_ROTC', 'NSTP/ROTC'), ('INTERNATIONAL_RELATIONS', 'International Relations Office'), ('SPORTS_CULTURAL', 'Sports and Cultural Development'), ('LEGAL_SERVICES', 'Legal Services Office'), ('PERSONNEL_SCHOLARSHIP', 'Personnel Scholarship Office'), ('QUALITY_ASSURANCE', 'Quality Assurance Office'), ('OFFICE_VPAA', 'Office of the VPAA'), ('OFFICE_VPAF', 'Office of the VPAF'), ('OFFICE_VPREICWKM', 'Office of the VPREICWKM'), ('OFFICE_BSB', 'Office of the Board Secretary/BOT'), ('PLANNING', 'Planning'), ('QUALITY_ASSURANCE', 'Quality Assurance'), ('ISO', 'ISO'), ('MIS', 'MIS'), ('SCUAA', 'SCUAA'), ('CSC', 'CSC'), ('CRCYC', 'CRCYC'), ('GAD', 'GAD'), ('PIO', 'PIO')], max_length=50, null=True, unique=True),
        ),
    ]
